### ISSUE TITLE
在推理一个1分40左右的音频时显存爆了

### ISSUE THREAD

**Issue by gongfusanhao** [yerfor/Real3DPortrait#13]
如题

**Comment by yerfor** [comment]
你好，可以提供报错的截图吗？以及您的GPU型号。方便我们定位问题

**Comment by gongfusanhao** [comment]
Real3D-Portrait is rendering frames: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1844/1844 [02:06<00:00, 14.60it/s]
Traceback (most recent call last):
  File "/root/Real3DPortrait-main/real3d_infer.py", line 599, in <module>
    GeneFace2Infer.example_run(inp)
  File "/root/Real3DPortrait-main/real3d_infer.py", line 537, in example_run
    infer_instance.infer_once(inp)
  File "/root/Real3DPortrait-main/real3d_infer.py", line 185, in infer_once
    out_name = self.forward_system(samples, inp)
  File "/root/miniconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/Real3DPortrait-main/real3d_infer.py", line 523, in forward_system
    out_fname = self.forward_secc2video(batch, inp)
  File "/root/miniconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/Real3DPortrait-main/real3d_infer.py", line 475, in forward_secc2video
    secc_img = torch.cat([torch.nn.functional.interpolate(drv_secc_colors[i:i+1], (512,512)) for i in range(num_frames)])
  File "/root/Real3DPortrait-main/real3d_infer.py", line 475, in <listcomp>
    secc_img = torch.cat([torch.nn.functional.interpolate(drv_secc_colors[i:i+1], (512,512)) for i in range(num_frames)])
  File "/root/miniconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.65 GiB total capacity; 21.50 GiB already allocated; 8.06 MiB free; 22.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by gongfusanhao** [comment]
gpu是在autodl上租的RTX4090

**Comment by Kizuna-AII** [comment]
We have updated the code and you can try `--low_memory_usage` in CLI inference.
We hope this option can solve your problem.
