### ISSUE TITLE
RuntimeError: Unknown layout

### ISSUE THREAD

**Issue by buaajjg** [yerfor/Real3DPortrait#34]
这个问题有遇到过的吗？怎么解决
`
(real3dportrait) root@VM-0-5-ubuntu:/home/autopai/jjg/Real3DPortrait# python inference/real3d_infer.py --src_img data/raw/examples/Macron.png --drv_aud data/raw/examples/Obama_5s.wav --drv_pose data/raw/examples/May_5s.mp4 --bg_img data/raw/examples/bg.png --out_name output.mp4 --out_mode concat_debug --low_memory_usage
| WARN: egs/egs_bases/audio2motion/vae.yaml not exist.
| WARN: checkpoints/240210_real3dportrait_orig/th1kh_512_audio2motion/base.yaml not exist.
| load 'model' from 'checkpoints/240210_real3dportrait_orig/audio2secc_vae/model_ckpt_steps_400000.ckpt', strict=True
| WARN: checkpoints/240210_real3dportrait_orig/secc2plane_torso_orig/secc_img2plane_orig.yaml not exist.
| load 'model' from 'checkpoints/240210_real3dportrait_orig/secc2plane_torso_orig/model_ckpt_steps_100000.ckpt', strict=True
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1709718794.396305    2338 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1709718794.497222    2465 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.105.17), renderer: Tesla T4/PCIe/SSE2
W0000 00:00:1709718794.501735    2338 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
face area percent 0.22489264198096937 larger than threshold 0.2, directly use the input image...
Extracted wav file (16khz) from data/raw/examples/Obama_5s.wav to data/raw/examples/Obama_5s_16k.wav.
Loading the HuBERT Model...
Some weights of HubertModel were not initialized from the model checkpoint at facebook/hubert-large-ls960-ft and are newly initialized: ['hubert.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'hubert.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading the Wav2Vec2 Processor...
I0000 00:00:1709718804.534568    2338 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1709718804.598764    2580 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.105.17), renderer: Tesla T4/PCIe/SSE2
I0000 00:00:1709718805.212283    2338 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1709718805.269880    2600 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.105.17), renderer: Tesla T4/PCIe/SSE2
W0000 00:00:1709718805.270366    2338 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
batch 0 | loss_lan: 0.40, loss_reg_id: 0.27,loss_reg_exp: 0.97
| To extract pose from data/raw/examples/May_5s.mp4
lms_2d file not found, try to extract it from video... data/raw/examples/May_5s_lms.npy
I0000 00:00:1709718807.209767    2338 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1709718807.265839    2640 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.105.17), renderer: Tesla T4/PCIe/SSE2
W0000 00:00:1709718807.266191    2338 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
I0000 00:00:1709718807.290557    2338 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1709718807.352956    2649 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.105.17), renderer: Tesla T4/PCIe/SSE2
W0000 00:00:1709718807.353318    2338 face_landmarker_graph.cc:174] Sets FaceBlendshapesGraph acceleration to xnnpack by default.
| Extracted pose from data/raw/examples/May_5s.mp4
{'drv_audio_name': 'data/raw/examples/Obama_5s.wav', 'src_image_name': 'infer_out/tmp/cropped_src_img.png', 'a2m_ckpt': 'checkpoints/240210_real3dportrait_orig/audio2secc_vae', 'head_ckpt': '', 'torso_ckpt': 'checkpoints/240210_real3dportrait_orig/secc2plane_torso_orig', 'bg_image_name': 'data/raw/examples/bg.png', 'drv_pose_name': 'data/raw/examples/May_5s.mp4', 'blink_mode': 'period', 'temperature': 0.2, 'mouth_amp': 0.45, 'out_name': 'output.mp4', 'out_mode': 'concat_debug', 'map_to_init_pose': 'True', 'head_torso_threshold': None, 'seed': None, 'min_face_area_percent': 0.2, 'low_memory_usage': True}
| audio-to-motion finished
rendering drv secc:   0%|                                                                              | 0/3 [00:00<?, ?it/s]create rasterizer on device cuda:0
rendering drv secc:   0%|                                                                              | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/autopai/jjg/Real3DPortrait/inference/real3d_infer.py", line 625, in <module>
    GeneFace2Infer.example_run(inp)
  File "/home/autopai/jjg/Real3DPortrait/inference/real3d_infer.py", line 561, in example_run
    infer_instance.infer_once(inp)
  File "/home/autopai/jjg/Real3DPortrait/inference/real3d_infer.py", line 187, in infer_once
    out_name = self.forward_system(samples, inp)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/autopai/jjg/Real3DPortrait/inference/real3d_infer.py", line 546, in forward_system
    self.forward_audio2secc(batch, inp)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/autopai/jjg/Real3DPortrait/inference/real3d_infer.py", line 385, in forward_audio2secc
    batch = self.get_driving_motion(batch['id'], batch['exp'], batch['euler'], batch['trans'], batch, inp)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/autopai/jjg/Real3DPortrait/inference/real3d_infer.py", line 401, in get_driving_motion
    face_mask, drv_secc_color = self.secc_renderer(id[i*chunk_size:(i+1)*chunk_size], exp[i*chunk_size:(i+1)*chunk_size], zero_eulers[i*chunk_size:(i+1)*chunk_size], zero_trans[i*chunk_size:(i+1)*chunk_size])
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/autopai/jjg/Real3DPortrait/./deep_3drecon/secc_renderer.py", line 50, in forward
    face_mask, _, secc_face = self.face_renderer(
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/autopai/jjg/Real3DPortrait/./deep_3drecon/util/mesh_renderer.py", line 110, in forward
    fragments = self.rasterizer(mesh, cameras = cameras, raster_settings = raster_settings)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 252, in forward
    pix_to_face, zbuf, bary_coords, dists = rasterize_meshes(
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 223, in rasterize_meshes
    pix_to_face, zbuf, barycentric_coords, dists = _RasterizeFaceVerts.apply(
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/autopai/anaconda3/envs/real3dportrait/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 297, in forward
    pix_to_face, zbuf, barycentric_coords, dists = _C.rasterize_meshes(
RuntimeError: Unknown layout
`

**Comment by Kizuna-AII** [comment]
Hi, maybe your `Pytorch3D` is not well installed.
In this case, we recommend you to re-create a new conda environment and install `Pytorch3D` from source code:
```bash
pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
```
It will takes a long time, but has a better compatibility.

**Comment by buaajjg** [comment]
> Hi, maybe your `Pytorch3D` is not well installed. In this case, we recommend you to re-create a new conda environment and install `Pytorch3D` from source code:
> 
> ```shell
> pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"
> ```
> 
> It will takes a long time, but has a better compatibility.

I reinstall pytorch3d with conda,  it works well now.  Many Thanks to u
