### ISSUE TITLE
复现推理失败

### ISSUE THREAD

**Issue by copgdjj** [yerfor/Real3DPortrait#42]
(real3dportrait) root@I18ed016ef200101884:/Real3DPortrait# python inference/real3d_infer.py --src_img data/raw/examples/Macron.png --drv_aud data/raw/examples/Obama_5s.wav --drv_pose data/raw/examples/May_5s.mp4 --bg_img data/raw/examples/bg.png --out_name output.mp4 --out_mode concat_debug
| WARN: egs/egs_bases/audio2motion/vae.yaml not exist.
| WARN: checkpoints/240210_real3dportrait_orig/th1kh_512_audio2motion/base.yaml not exist.
| load 'model' from 'checkpoints/240210_real3dportrait_orig/audio2secc_vae/model_ckpt_steps_400000.ckpt', strict=True
| WARN: egs/egs_bases/audio2motion/vae.yaml not exist.
| WARN: checkpoints/240210_real3dportrait_orig/th1kh_512_audio2motion/base.yaml not exist.
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpbkqnubjo
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpbkqnubjo/_remote_module_non_scriptable.py
Traceback (most recent call last):
  File "/Real3DPortrait/inference/real3d_infer.py", line 625, in <module>
    GeneFace2Infer.example_run(inp)
  File "/Real3DPortrait/inference/real3d_infer.py", line 560, in example_run
    infer_instance = cls(inp['a2m_ckpt'], inp['head_ckpt'], inp['torso_ckpt'], inp=inp)
  File "/Real3DPortrait/inference/real3d_infer.py", line 118, in __init__
    self.secc2video_model = self.load_secc2video(head_model_dir, torso_model_dir, inp)
  File "/Real3DPortrait/inference/real3d_infer.py", line 163, in load_secc2video
    model = OSAvatarSECC_Img2plane_Torso()
  File "/Real3DPortrait/./modules/real3d/secc_img2plane_torso.py", line 9, in __init__
    super().__init__(hp=hp)
  File "/Real3DPortrait/./modules/real3d/secc_img2plane.py", line 26, in __init__
    super().__init__(hp=hp)
  File "/Real3DPortrait/./modules/real3d/img2plane_baseline.py", line 89, in __init__
    self.w_dim = hparams['w_dim']
KeyError: 'w_dim'

**Comment by 1184919257** [comment]
裁剪头部区域，resize 512*512

**Comment by yerfor** [comment]
看起来是secc_img2plane_torso模型的config.yaml没有被正确load，可以检查一下路径。
